name: 'Quickstart Playwright End to End Tests'
description: 'Standardized Playwright end to end test for all FusionAuth Quickstart applications.'
inputs:
  FUSIONAUTH_ADMIN_URL:
    description: 'The URL of the FusionAuth admin interface.'
    required: false
    default: 'http://localhost:9011/admin'
  QUICKSTART_URL:
    description: 'The URL of the Quickstart application.'
    required: false
    default: 'http://localhost:3000'
  ARTIFACT_PREFIX:
    description: 'The prefix for the generated playwright artifact. Especially useful for matrix workflows.'
    required: false
    default: 'playwright'
runs:
  using: "composite"
  steps:
    - name: Action Path
      run: echo $ACTION_PATH
      env:
        ACTION_PATH: ${{ github.action_path }}
      shell: bash

    - name: Action Repository
      run: echo $ACTION_REPOSITORY
      env:
        ACTION_PATH: ${{ github.action_repository }}
      shell: bash

    - name: Action Ref
      run: echo $ACTION_REF
      env:
        ACTION_PATH: ${{ github.action_ref }}
      shell: bash

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Run Playwright tests
      run: npx playwright test
      env:
        FUSIONAUTH_ADMIN_URL: ${{ inputs.FUSIONAUTH_ADMIN_URL }}
        QUICKSTART_URL: ${{ inputs.QUICKSTART_URL }}
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Upload Playwright results
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: ${{ inputs.ARTIFACT_PREFIX }}-report-${{github.run_number}}-${{github.run_attempt}}
        path: ${{ github.action_path }}/playwright-report/
        retention-days: 30
